#!/usr/bin/env bash
# 0.3

# exit as soon as a test fails
set -e

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2


validate_jenkinsfile() {
    if [[ $1 =~ "Jenkinsfile" ]]; then
        echo "Validating Jenkins Groovy file $file"
        lint-jenkins.sh $file
    fi
}

validate_jinja() {
    if [[ $1 =~ ".yml" ]] || [[ $1 =~ ".yaml" ]]; then
        echo "Validating Jinja file $file"
        validate_jinja.py $file
    fi
}

validate_python() {
    if [[ $1 =~ ".py" ]]; then
        echo "Validating Python file $file"
        pylint $file || pylint-exit --error-fail $?
    fi
}

validate_rst() {
    if [[ $file =~ "*.rst" ]] || [[ $file =~ "*.rest" ]]; then
        echo "Validating reStructuredText file $file"
        rst-lint $file
    fi
}

validate_files() {
    for file in $(git diff --cached --name-only $against); do
        validate_jenkinsfile $file
        validate_jinja $file
        validate_python $file
        validate_rst $file
    done
}

validate_files
